name: APAI-exam
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch
  - torchvision
  - pytorch-cuda=11.8
  - numpy
  - matplotlib
  - tqdm
  - scikit-learn
  - pip
  - pip:
    - transformers
    - open_clip_torch>=2.20.0
    - POT>=0.9.0
    - wandb>=0.15.0
    - certifi